name: Release workflow

on:
  release:
    types: [published]

jobs:
  deploy_production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Check README
      run: |
        cat README.md
    
